"""Adicionar descrição opcional aos consumos

Revision ID: 54399b571f87
Revises: b49a94215a01
Create Date: 2026-05-04 20:59:02.333116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54399b571f87'
down_revision: Union[str, Sequence[str], None] = 'b49a94215a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption_history', sa.Column('description', sa.String(length=280), nullable=True))
    op.add_column('consumption_simulations', sa.Column('description', sa.String(length=280), nullable=True))
    op.add_column('goals', sa.Column('description', sa.String(length=280), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'description')
    op.drop_column('consumption_simulations', 'description')
    op.drop_column('consumption_history', 'description')
    # ### end Alembic commands ###
