"""fix: Implementação de nova lógica de cascade em deleções no banco de dados

Revision ID: b49a94215a01
Revises: cb1b7599fb7a
Create Date: 2026-04-26 15:34:24.978772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49a94215a01'
down_revision: Union[str, Sequence[str], None] = 'cb1b7599fb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
