"""Atualizando o modelo de dica para receber JSON consumido

Revision ID: 33e0fa2f0c4e
Revises: a84234f16205
Create Date: 2026-03-03 19:45:38.020792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e0fa2f0c4e'
down_revision: Union[str, Sequence[str], None] = 'a84234f16205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'tips', ['tip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tips', type_='unique')
    op.drop_column('tips', 'created_at')
    # ### end Alembic commands ###
