"""Reiniciando revisão para troca do banco de dados e correção do erro originado pelo Base.metadata.create_all no ambiente de dev antigo

Revision ID: cb1b7599fb7a
Revises: 
Create Date: 2026-04-20 17:37:33.221249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1b7599fb7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('si_measurement_unit', sa.String(length=50), nullable=False),
    sa.Column('tip', sa.String(length=280), nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tip')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consumption_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('ending_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('si_measurement_unit', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumption_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('ending_date', sa.Date(), nullable=False),
    sa.Column('si_measurement_unit', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('ending_date', sa.Date(), nullable=False),
    sa.Column('si_measurement_unit', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.drop_table('consumption_simulations')
    op.drop_table('consumption_history')
    op.drop_table('users')
    op.drop_table('tips')
    # ### end Alembic commands ###
