"""Criação de default para colunas temporais e especificação de zero em entradas nulas de gasto

Revision ID: ffa8600dc9aa
Revises: fb73a131f461
Create Date: 2026-02-04 09:01:01.129448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffa8600dc9aa'
down_revision: Union[str, Sequence[str], None] = 'fb73a131f461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consumption_history', 'ending_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('consumption_history', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('consumption_simulations', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('goals', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('tips', sa.Column('si_measurement_unit', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('tips', 'si_measurement_unit')
    op.alter_column('goals', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('consumption_simulations', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('consumption_history', 'value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('consumption_history', 'ending_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
