"""Atualizando o backend para refletir as alterações mais recentes na Models e para garantir a última migração do backend base

Revision ID: 19589b1c8018
Revises: 33e0fa2f0c4e
Create Date: 2026-04-20 11:33:44.173932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19589b1c8018'
down_revision: Union[str, Sequence[str], None] = '33e0fa2f0c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
